# Generated by Django 5.1.2 on 2024-11-07 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruder', '0002_teacher_remove_book_available_remove_book_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_1730965012038', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
