# Generated by Django 5.1.3 on 2024-12-23 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruder', '0003_person_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anania', models.TextField(max_length=200)),
            ],
        ),
    ]
