# Generated by Django 5.1.3 on 2024-11-24 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruder', '0003_person_delete_teacher'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accoun_number', models.CharField(max_length=50)),
                ('balance', models.CharField(max_length=150)),
            ],
        ),
    ]
