# Generated by Django 5.1.3 on 2024-12-23 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cruder', '0004_sample'),
    ]

    operations = [
        migrations.CreateModel(
            name='firstyghjfgjh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anania', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='qwertyu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anania', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='qwertyuawwwxe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anania', models.TextField(max_length=200)),
            ],
        ),
    ]
