# Generated by Django 5.1.3 on 2024-12-24 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cruder', '0005_firstyghjfgjh_qwertyu_qwertyuawwwxe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='firstyghjfgjh',
        ),
        migrations.DeleteModel(
            name='qwertyu',
        ),
        migrations.DeleteModel(
            name='qwertyuawwwxe',
        ),
        migrations.DeleteModel(
            name='sample',
        ),
    ]
