# Generated by Django 5.1.3 on 2024-12-23 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0003_dynamicmodellog'),
        ('idd', '0009_alter_application_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicmodellog',
            name='application',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='idd.application'),
        ),
    ]
