# Generated by Django 5.1.3 on 2024-12-23 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0004_dynamicmodellog_application'),
        ('idd', '0009_alter_application_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicmodellog',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='idd.application'),
        ),
    ]
