# Generated by Django 5.1.2 on 2024-11-07 08:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(max_length=50)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=50)),
                ('text_content', models.TextField(blank=True)),
                ('django_tag_type', models.CharField(blank=True, choices=[('csrf_token', 'CSRF Token'), ('for', 'For Loop'), ('endfor', 'End For Loop'), ('if', 'If Condition'), ('endif', 'End If Condition'), ('block', 'Block Tag'), ('endblock', 'End Block Tag'), ('extends', 'Extends Tag')], max_length=50, null=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('parent_tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='idd.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('tag', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='idd.tag')),
            ],
        ),
        migrations.CreateModel(
            name='TagClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idd.class')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tagclasses', to='idd.tag')),
            ],
            options={
                'unique_together': {('tag', 'class_name')},
            },
        ),
        migrations.AddField(
            model_name='tag',
            name='classes',
            field=models.ManyToManyField(related_name='tags', through='idd.TagClass', to='idd.class'),
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idd.application')),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='idd.template'),
        ),
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute_name', models.CharField(max_length=50)),
                ('attribute_value', models.CharField(max_length=255)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='idd.tag')),
            ],
            options={
                'unique_together': {('tag', 'attribute_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('position', 'parent_tag')},
        ),
    ]
