# Generated by Django 5.1.3 on 2024-11-27 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idd', '0002_templatecategory_templates'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Templates',
            new_name='TemplatesOwnership',
        ),
    ]
