# Generated by Django 5.1.3 on 2024-12-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idd', '0003_rename_templates_templatesownership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
