# Generated by Django 5.1.3 on 2024-12-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idd', '0004_alter_class_class_name'),
        ('idd', '0005_project'),
    ]

    operations = [
    ]
