# Generated by Django 5.1.3 on 2024-12-06 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idd', '0006_merge_0004_alter_class_class_name_0005_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(blank=True, choices=[('CATEGORY_1', 'Category 1'), ('CATEGORY_2', 'Category 2'), ('CATEGORY_3', 'Category 3')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='applications',
            field=models.ManyToManyField(related_name='projects', to='idd.application'),
        ),
        migrations.DeleteModel(
            name='TemplateCategory',
        ),
    ]
