# Generated by Django 5.1.3 on 2024-12-08 20:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idd', '0007_alter_template_category_project_applications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='application',
            name='description',
            field=models.TextField(default=' Description Not Available'),
        ),
    ]
