# Generated by Django 5.1.3 on 2024-12-08 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idd', '0008_application_created_at_application_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='application',
            name='description',
            field=models.TextField(),
        ),
    ]
