# Generated by Django 5.1.3 on 2024-12-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idd', '0010_alter_template_category'),
        ('idd', '0010_like'),
    ]

    operations = [
    ]
