# Generated by Django 5.1.3 on 2024-12-24 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idd', '0010_like'),
        ('idd', '0011_alter_template_category'),
    ]

    operations = [
    ]
