# Generated by Django 5.0.4 on 2024-10-15 05:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_input', models.JSONField()),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('uploaded_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.uploadedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('charfield', 'Text Input'), ('file', 'File Input'), ('image', 'Image Input'), ('json', 'JSON Input')], max_length=100)),
                ('label', models.CharField(max_length=255)),
                ('required', models.BooleanField(default=True)),
                ('max_size', models.IntegerField(blank=True, null=True)),
                ('uploaded_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='database.uploadedmodel')),
            ],
        ),
        migrations.CreateModel(
            name='ModelFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='models/files/')),
                ('file_type', models.CharField(choices=[('model_file', 'Model File'), ('weights', 'Weights'), ('config', 'Config File')], max_length=100)),
                ('uploaded_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='database.uploadedmodel')),
            ],
        ),
    ]
