# Generated by Django 5.0.6 on 2024-10-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelinput',
            name='uploaded_model',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='tester',
        ),
        migrations.RemoveField(
            model_name='testsession',
            name='uploaded_model',
        ),
        migrations.RemoveField(
            model_name='uploadedmodel',
            name='user',
        ),
        migrations.DeleteModel(
            name='ModelFile',
        ),
        migrations.DeleteModel(
            name='ModelInput',
        ),
        migrations.DeleteModel(
            name='TestSession',
        ),
        migrations.DeleteModel(
            name='UploadedModel',
        ),
    ]
